CREATE TABLE IF NOT EXISTS timetable_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id INTEGER NOT NULL REFERENCES routes(id) ON DELETE CASCADE,
    stop_id INTEGER NOT NULL REFERENCES stops(id) ON DELETE CASCADE,
    scheduled_arrival TIME NOT NULL,
    scheduled_departure TIME NOT NULL,
    day_mask SMALLINT NOT NULL DEFAULT 127,
    effective_from DATE NOT NULL DEFAULT CURRENT_DATE,
    effective_to DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_timetable_effective_window
        CHECK (effective_to IS NULL OR effective_to >= effective_from)
);

CREATE INDEX IF NOT EXISTS idx_timetable_route_stop
    ON timetable_entries (route_id, stop_id);
