extends: default

ignore: |
  epic-05-cicd/helm/**/templates/*.yaml

rules:
  empty-lines:
    max: 3
    max-start: 2
    max-end: 2
  comments: disable
  comments-indentation: disable
  document-start: disable
  line-length:
    max: 140
    level: warning
  truthy:
    allowed-values: ["true", "false", "on", "off", "yes", "no"]
