# hivemq-headless-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: hivemq-headless
  namespace: transit-edge
  labels:
    app: hivemq
spec:
  clusterIP: None
  ports:
    - port: 1883
      name: mqtt
    - port: 8883
      name: mqtts
  selector:
    app: hivemq