# Secrets for Keycloak:
# - The keycloak-db secret aligns with the DB user and password from epic-03-data/k8s/postgres-statefulset.yaml:
#   - Username: transit_admin (POSTGRES_USER)
#   - Password: must match the POSTGRES_PASSWORD value in the postgres-credentials secret in the transit-data namespace
#   - Database: keycloak_db (created by the postgres-init-script init.sql)
#
# - The keycloak-admin secret is for Keycloak's admin (bootstrap) user. 
#   should replace the encoded values ("username" and "password") with secure credentials before deploying to staging or production.

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  namespace: transit-platform
  labels:
    app: keycloak
    app.kubernetes.io/part-of: ontime
type: Opaque
data:
  username: YWRtaW4=
  password: Y2hhbmdlbWUta2V5Y2xvYWstYWRtaW4=

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db
  namespace: transit-platform
  labels:
    app: keycloak
    app.kubernetes.io/part-of: ontime
type: Opaque
data:
  username: dHJhbnNpdF9hZG1pbg==
  password: c3VwZXJzZWN1cmVwYXNzd29yZA==
