prometheus:
  prometheusSpec:
    # Set Prometheus data retention to 15 days for Increment 1
    retention: 15d
    # Configure to discover ServiceMonitors across namespaces without strict label matching
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

grafana:
  admin:
    existingSecret: monitoring-grafana-auth
    userKey: admin-user
    passwordKey: admin-password
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
      serve_from_sub_path: true
