apiVersion: apps/v1
kind: Deployment

metadata:
  name: kong-gateway
  labels:
    app: kong-gateway

spec:
  replicas: 2
  selector:
    matchLabels:
      app: kong-gateway
  template:
    metadata:
      labels:
        app: kong-gateway
    spec:
      containers:
        - name: kong
          image: kong:3.4-ubuntu
          env:
            - name: KONG_DATABASE
              value: "off"                    # dbless mode
            - name: KONG_DECLARATIVE_CONFIG
              value: "/kong_config/kong.yml"  # reads from the ConfigMap Kustomize generates!
            - name: KONG_PROXY_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_ADMIN_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_PROXY_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_LISTEN         # Required so the Admin API listens on all internal connections
              value: "0.0.0.0:8001"
          ports:
            - name: proxy
              containerPort: 8000
            - name: admin
              containerPort: 8001

          # Acceptance Criteria: Health Probes hitting /status on port 8001
          livenessProbe:
            httpGet:
              path: /status
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /status
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
            
          # IMPORTANT: The HPA auto-scaler will not work unless we define resource requests!
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
              
          volumeMounts:
            - name: kong-config-volume
              mountPath: /kong_config
      volumes:
        - name: kong-config-volume
          configMap:
            name: kong-declarative-config # This MUST match the name in Kustomization