---
apiVersion: v1
kind: Namespace
metadata:
  name: transit-platform
  labels:
    app.kubernetes.io/part-of: ontime
---
apiVersion: v1
kind: Namespace
metadata:
  name: transit-edge
  labels:
    app.kubernetes.io/part-of: ontime
---
apiVersion: v1
kind: Namespace
metadata:
  name: transit-streaming
  labels:
    app.kubernetes.io/part-of: ontime
---
apiVersion: v1
kind: Namespace
metadata:
  name: transit-intelligence
  labels:
    app.kubernetes.io/part-of: ontime
---
apiVersion: v1
kind: Namespace
metadata:
  name: transit-ui
  labels:
    app.kubernetes.io/part-of: ontime

