# TODO: Implement according to G4 guide and issue assignment.

apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: transit-data
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgresql
