_format_version: "3.0"
_transform: true

# kong-proxy is LoadBalancer type but Minikube doesn't have a LoadBalancer controller, 
# so the external IP never gets assigned. browser can't reach it because there's no actual external IP.
# To test locally:
#   kubectl port-forward -n transit-platform svc/kong-proxy 8088:80
#   then open http://127.0.0.1:8088/auth/admin/

services:
  - name: ontime-api
    url: http://ontime-api:8000
    routes:
      - name: ontime-api-route
        paths:
          - /api/v1/ontime
          - /api/v1/ontime/*
        methods:
          - GET
          - POST
          - PUT
          - DELETE

  - name: kong-status
    url: http://localhost:8001
    routes:
      - name: health-route
        paths:
          - /health
        methods:
          - HEAD
          - GET

  - name: keycloak-auth
    url: http://keycloak-service:8080
    routes:
      - name: keycloak-auth-route
        preserve_host: true
        paths:
          - /auth
          - /auth/*
        methods:
          - HEAD
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
          - OPTIONS
        strip_path: false
