# yamllint disable rule:braces
# yamllint disable rule:syntax
{{- range $name, $svc := .Values.services }}
{{- if $svc.secrets }}
{{- $fullName := printf "%s-g2-%s" $.Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- $secretName := default $fullName $svc.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $secretName }}"
  labels:
    app.kubernetes.io/name: "{{ $fullName }}"
    app.kubernetes.io/instance: "{{ $.Release.Name }}"
    app.kubernetes.io/component: "{{ $name }}"
type: Opaque
stringData:
  {{- range $key, $value := $svc.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
